import Foundation

/// Homepage generator (combines blog + links)
public class HomepageGenerator: Generator {
    private let posts: [BlogPostEntity]
    private let links: [LinkItemEntity]

    /// - Parameters:
    ///   - posts: Blog posts already generated by the blog pipeline.
    ///   - links: Links already generated by the links pipeline.
    public init(posts: [BlogPostEntity], links: [LinkItemEntity]) {
        self.posts = posts
        self.links = links
    }

    // MARK: - Generator Protocol

    public func generate() throws {
        print("#", String(repeating: "-", count: 80))
        print("Building homepage...")

        let fileRepository = LocalFileRepository(basePath: Config.releasePath)
        let templateRepository = try StencilTemplateRepository(templatePath: Config.templatePath)
        let useCase = GenerateHomepageUseCase(
            fileRepository: fileRepository,
            templateRepository: templateRepository
        )

        try useCase.execute(posts: posts, links: links)

        print("✅ Homepage generation complete!")
    }
}
